#!/bin/bash
mv    err_typecheck_add_character_floating.bilby    good_formerly_err_typecheck_add_character_floating.bilby    
mv    err_typecheck_add_character_integer.bilby    good_formerly_err_typecheck_add_character_integer.bilby    
mv    err_typecheck_add_floating_character.bilby    good_formerly_err_typecheck_add_floating_character.bilby    
mv    err_typecheck_add_floating_integer.bilby    good_formerly_err_typecheck_add_floating_integer.bilby    
mv    err_typecheck_add_integer_character.bilby    good_formerly_err_typecheck_add_integer_character.bilby    
mv    err_typecheck_add_integer_floating.bilby    good_formerly_err_typecheck_add_integer_floating.bilby    
mv    err_typecheck_divide_character_floating.bilby    good_formerly_err_typecheck_divide_character_floating.bilby    
mv    err_typecheck_divide_character_integer.bilby    good_formerly_err_typecheck_divide_character_integer.bilby    
mv    err_typecheck_divide_floating_character.bilby    good_formerly_err_typecheck_divide_floating_character.bilby    
mv    err_typecheck_divide_floating_integer.bilby    good_formerly_err_typecheck_divide_floating_integer.bilby    
mv    err_typecheck_divide_integer_character.bilby    good_formerly_err_typecheck_divide_integer_character.bilby    
mv    err_typecheck_divide_integer_floating.bilby    good_formerly_err_typecheck_divide_integer_floating.bilby    
mv    err_typecheck_equals_character_floating.bilby    good_formerly_err_typecheck_equals_character_floating.bilby    
mv    err_typecheck_equals_character_integer.bilby    good_formerly_err_typecheck_equals_character_integer.bilby    
mv    err_typecheck_equals_floating_character.bilby    good_formerly_err_typecheck_equals_floating_character.bilby    
mv    err_typecheck_equals_floating_integer.bilby    good_formerly_err_typecheck_equals_floating_integer.bilby    
mv    err_typecheck_equals_integer_character.bilby    good_formerly_err_typecheck_equals_integer_character.bilby    
mv    err_typecheck_equals_integer_floating.bilby    good_formerly_err_typecheck_equals_integer_floating.bilby    
mv    err_typecheck_greater_character_floating.bilby    good_formerly_err_typecheck_greater_character_floating.bilby    
mv    err_typecheck_greater_character_integer.bilby    good_formerly_err_typecheck_greater_character_integer.bilby    
mv    err_typecheck_greater_equals_character_floating.bilby    good_formerly_err_typecheck_greater_equals_character_floating.bilby    
mv    err_typecheck_greater_equals_character_integer.bilby    good_formerly_err_typecheck_greater_equals_character_integer.bilby    
mv    err_typecheck_greater_equals_floating_character.bilby    good_formerly_err_typecheck_greater_equals_floating_character.bilby    
mv    err_typecheck_greater_equals_floating_integer.bilby    good_formerly_err_typecheck_greater_equals_floating_integer.bilby    
mv    err_typecheck_greater_equals_integer_character.bilby    good_formerly_err_typecheck_greater_equals_integer_character.bilby    
mv    err_typecheck_greater_equals_integer_floating.bilby    good_formerly_err_typecheck_greater_equals_integer_floating.bilby    
mv    err_typecheck_greater_floating_character.bilby    good_formerly_err_typecheck_greater_floating_character.bilby    
mv    err_typecheck_greater_floating_integer.bilby    good_formerly_err_typecheck_greater_floating_integer.bilby    
mv    err_typecheck_greater_integer_character.bilby    good_formerly_err_typecheck_greater_integer_character.bilby    
mv    err_typecheck_greater_integer_floating.bilby    good_formerly_err_typecheck_greater_integer_floating.bilby    
mv    err_typecheck_less_character_floating.bilby    good_formerly_err_typecheck_less_character_floating.bilby    
mv    err_typecheck_less_character_integer.bilby    good_formerly_err_typecheck_less_character_integer.bilby    
mv    err_typecheck_less_equals_character_floating.bilby    good_formerly_err_typecheck_less_equals_character_floating.bilby    
mv    err_typecheck_less_equals_character_integer.bilby    good_formerly_err_typecheck_less_equals_character_integer.bilby    
mv    err_typecheck_less_equals_floating_character.bilby    good_formerly_err_typecheck_less_equals_floating_character.bilby    
mv    err_typecheck_less_equals_floating_integer.bilby    good_formerly_err_typecheck_less_equals_floating_integer.bilby    
mv    err_typecheck_less_equals_integer_character.bilby    good_formerly_err_typecheck_less_equals_integer_character.bilby    
mv    err_typecheck_less_equals_integer_floating.bilby    good_formerly_err_typecheck_less_equals_integer_floating.bilby    
mv    err_typecheck_less_floating_character.bilby    good_formerly_err_typecheck_less_floating_character.bilby    
mv    err_typecheck_less_floating_integer.bilby    good_formerly_err_typecheck_less_floating_integer.bilby    
mv    err_typecheck_less_integer_character.bilby    good_formerly_err_typecheck_less_integer_character.bilby    
mv    err_typecheck_less_integer_floating.bilby    good_formerly_err_typecheck_less_integer_floating.bilby    
mv    err_typecheck_multiply_character_floating.bilby    good_formerly_err_typecheck_multiply_character_floating.bilby    
mv    err_typecheck_multiply_character_integer.bilby    good_formerly_err_typecheck_multiply_character_integer.bilby    
mv    err_typecheck_multiply_floating_character.bilby    good_formerly_err_typecheck_multiply_floating_character.bilby    
mv    err_typecheck_multiply_floating_integer.bilby    good_formerly_err_typecheck_multiply_floating_integer.bilby    
mv    err_typecheck_multiply_integer_character.bilby    good_formerly_err_typecheck_multiply_integer_character.bilby    
mv    err_typecheck_multiply_integer_floating.bilby    good_formerly_err_typecheck_multiply_integer_floating.bilby    
mv    err_typecheck_not_equals_character_floating.bilby    good_formerly_err_typecheck_not_equals_character_floating.bilby    
mv    err_typecheck_not_equals_character_integer.bilby    good_formerly_err_typecheck_not_equals_character_integer.bilby    
mv    err_typecheck_not_equals_floating_character.bilby    good_formerly_err_typecheck_not_equals_floating_character.bilby    
mv    err_typecheck_not_equals_floating_integer.bilby    good_formerly_err_typecheck_not_equals_floating_integer.bilby    
mv    err_typecheck_not_equals_integer_character.bilby    good_formerly_err_typecheck_not_equals_integer_character.bilby    
mv    err_typecheck_not_equals_integer_floating.bilby    good_formerly_err_typecheck_not_equals_integer_floating.bilby    
mv    err_typecheck_subtract_character_floating.bilby    good_formerly_err_typecheck_subtract_character_floating.bilby    
mv    err_typecheck_subtract_character_integer.bilby    good_formerly_err_typecheck_subtract_character_integer.bilby    
mv    err_typecheck_subtract_floating_character.bilby    good_formerly_err_typecheck_subtract_floating_character.bilby    
mv    err_typecheck_subtract_floating_integer.bilby    good_formerly_err_typecheck_subtract_floating_integer.bilby    
mv    err_typecheck_subtract_integer_character.bilby    good_formerly_err_typecheck_subtract_integer_character.bilby    
mv    err_typecheck_subtract_integer_floating.bilby    good_formerly_err_typecheck_subtract_integer_floating.bilby    
